spring:
  application:
    name: hsbcuser-service

server:
  port: 8086
  tomcat:
    max-http-post-size: -1

logging:
  config: classpath:Spring-logback.xml
  level:
    web: DEBUG
    com.hsbc.user: trace






